services:
  scheduler-100-of-0-cpu:
    command: &id001
    - /bin/sh
    - -c
    - if [ -d /root/share_models/auto_openai/ ]; then cp -rf /root/share_models/auto_openai/auto_openai
      /app/auto_openai && python3 -m auto_openai.scheduler; else python3 -m auto_openai.scheduler;
      fi
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: embedding,rerank
      CPU_IMAGE_TYPE: NV
      GPU_TYPE: CPU
      LABEL: lm-server-1753761110-1199837203
      LM_SERVER_BASE_PORT: 30232
      NODE_GPU_TOTAL: '100'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ../conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-101-of-1-cpu:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: embedding,rerank
      CPU_IMAGE_TYPE: NV
      GPU_TYPE: CPU
      LABEL: lm-server-1753761110-147790054
      LM_SERVER_BASE_PORT: 30240
      NODE_GPU_TOTAL: '101'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
